//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Isicomp.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class IsicompParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, FORMAT=11, ID=12, OPER_TER=13, OPER_FAT=14, PONTUACAO=15, NUM=16, 
		OPE_RELAC=17, DIGIT=18, LETTER=19, T_NULL=20, T_STRING=21, T_CHAR=22, 
		T_BYTE=23, T_INT=24, T_FLOAT=25, T_DOUBLE=26, T_SOMA=27, T_SUBT=28, T_DIV=29, 
		T_MULT=30, T_MAIOR=31, T_MENOR=32, T_IGUAL=33, T_COMMA=34, T_APARENT=35, 
		T_FPARENT=36, T_ASPAS=37, T_DOT=38, T_UNDERS=39, T_ACHAVE=40, T_FCHAVE=41, 
		T_MAIOR_IGUAL=42, T_MENOR_IGUAL=43, T_IGUAL_RELAC=44, T_DIF=45, WS=46;
	public const int
		RULE_programa = 0, RULE_declare = 1, RULE_blococomando = 2, RULE_comando = 3, 
		RULE_exp_ter = 4, RULE_exp_fat = 5, RULE_exp_relacional = 6, RULE_termo = 7, 
		RULE_se = 8, RULE_atribua = 9, RULE_escreva = 10, RULE_leia = 11, RULE_enquanto = 12, 
		RULE_faca = 13, RULE_string = 14;
	public static readonly string[] ruleNames = {
		"programa", "declare", "blococomando", "comando", "exp_ter", "exp_fat", 
		"exp_relacional", "termo", "se", "atribua", "escreva", "leia", "enquanto", 
		"faca", "string"
	};

	private static readonly string[] _LiteralNames = {
		null, "'programa'", "'fimprog'", "'declare'", "'se'", "'entao'", "'senao'", 
		"'escreva'", "'leia'", "'enquanto'", "'faca'", null, null, null, null, 
		null, null, null, null, null, "'nulo'", "'string'", "'char'", "'byte'", 
		"'int'", "'float'", "'double'", "'+'", "'-'", "'/'", "'*'", "'>'", "'<'", 
		"':='", "','", "'('", "')'", "'\"'", "'.'", "'_'", "'{'", "'}'", "'>='", 
		"'<='", "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "FORMAT", 
		"ID", "OPER_TER", "OPER_FAT", "PONTUACAO", "NUM", "OPE_RELAC", "DIGIT", 
		"LETTER", "T_NULL", "T_STRING", "T_CHAR", "T_BYTE", "T_INT", "T_FLOAT", 
		"T_DOUBLE", "T_SOMA", "T_SUBT", "T_DIV", "T_MULT", "T_MAIOR", "T_MENOR", 
		"T_IGUAL", "T_COMMA", "T_APARENT", "T_FPARENT", "T_ASPAS", "T_DOT", "T_UNDERS", 
		"T_ACHAVE", "T_FCHAVE", "T_MAIOR_IGUAL", "T_MENOR_IGUAL", "T_IGUAL_RELAC", 
		"T_DIF", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Isicomp.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static IsicompParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public IsicompParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public IsicompParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramaContext : ParserRuleContext {
		public DeclareContext declare() {
			return GetRuleContext<DeclareContext>(0);
		}
		public BlococomandoContext blococomando() {
			return GetRuleContext<BlococomandoContext>(0);
		}
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public ProgramaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_programa; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterPrograma(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitPrograma(this);
		}
	}

	[RuleVersion(0)]
	public ProgramaContext programa() {
		ProgramaContext _localctx = new ProgramaContext(Context, State);
		EnterRule(_localctx, 0, RULE_programa);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30; Match(T__0);
			State = 31; declare();
			State = 32; blococomando();
			State = 33; Match(T__1);
			State = 34; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclareContext : ParserRuleContext {
		public ITerminalNode[] ID() { return GetTokens(IsicompParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(IsicompParser.ID, i);
		}
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public ITerminalNode[] T_COMMA() { return GetTokens(IsicompParser.T_COMMA); }
		public ITerminalNode T_COMMA(int i) {
			return GetToken(IsicompParser.T_COMMA, i);
		}
		public DeclareContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declare; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterDeclare(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitDeclare(this);
		}
	}

	[RuleVersion(0)]
	public DeclareContext declare() {
		DeclareContext _localctx = new DeclareContext(Context, State);
		EnterRule(_localctx, 2, RULE_declare);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 36; Match(T__2);
			State = 37; Match(ID);
			State = 42;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T_COMMA) {
				{
				{
				State = 38; Match(T_COMMA);
				State = 39; Match(ID);
				}
				}
				State = 44;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 45; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlococomandoContext : ParserRuleContext {
		public ComandoContext[] comando() {
			return GetRuleContexts<ComandoContext>();
		}
		public ComandoContext comando(int i) {
			return GetRuleContext<ComandoContext>(i);
		}
		public BlococomandoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blococomando; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterBlococomando(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitBlococomando(this);
		}
	}

	[RuleVersion(0)]
	public BlococomandoContext blococomando() {
		BlococomandoContext _localctx = new BlococomandoContext(Context, State);
		EnterRule(_localctx, 4, RULE_blococomando);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 47; comando();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 50;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComandoContext : ParserRuleContext {
		public LeiaContext leia() {
			return GetRuleContext<LeiaContext>(0);
		}
		public EscrevaContext escreva() {
			return GetRuleContext<EscrevaContext>(0);
		}
		public AtribuaContext atribua() {
			return GetRuleContext<AtribuaContext>(0);
		}
		public SeContext se() {
			return GetRuleContext<SeContext>(0);
		}
		public EnquantoContext enquanto() {
			return GetRuleContext<EnquantoContext>(0);
		}
		public FacaContext faca() {
			return GetRuleContext<FacaContext>(0);
		}
		public ComandoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comando; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterComando(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitComando(this);
		}
	}

	[RuleVersion(0)]
	public ComandoContext comando() {
		ComandoContext _localctx = new ComandoContext(Context, State);
		EnterRule(_localctx, 6, RULE_comando);
		try {
			State = 58;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__7:
				EnterOuterAlt(_localctx, 1);
				{
				State = 52; leia();
				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 2);
				{
				State = 53; escreva();
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 3);
				{
				State = 54; atribua();
				}
				break;
			case T__3:
				EnterOuterAlt(_localctx, 4);
				{
				State = 55; se();
				}
				break;
			case T__8:
				EnterOuterAlt(_localctx, 5);
				{
				State = 56; enquanto();
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 6);
				{
				State = 57; faca();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Exp_terContext : ParserRuleContext {
		public Exp_fatContext[] exp_fat() {
			return GetRuleContexts<Exp_fatContext>();
		}
		public Exp_fatContext exp_fat(int i) {
			return GetRuleContext<Exp_fatContext>(i);
		}
		public ITerminalNode[] OPER_TER() { return GetTokens(IsicompParser.OPER_TER); }
		public ITerminalNode OPER_TER(int i) {
			return GetToken(IsicompParser.OPER_TER, i);
		}
		public Exp_terContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exp_ter; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterExp_ter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitExp_ter(this);
		}
	}

	[RuleVersion(0)]
	public Exp_terContext exp_ter() {
		Exp_terContext _localctx = new Exp_terContext(Context, State);
		EnterRule(_localctx, 8, RULE_exp_ter);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60; exp_fat();
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OPER_TER) {
				{
				{
				State = 61; Match(OPER_TER);
				State = 62; exp_fat();
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Exp_fatContext : ParserRuleContext {
		public ITerminalNode NUM() { return GetToken(IsicompParser.NUM, 0); }
		public ITerminalNode[] OPER_FAT() { return GetTokens(IsicompParser.OPER_FAT); }
		public ITerminalNode OPER_FAT(int i) {
			return GetToken(IsicompParser.OPER_FAT, i);
		}
		public TermoContext[] termo() {
			return GetRuleContexts<TermoContext>();
		}
		public TermoContext termo(int i) {
			return GetRuleContext<TermoContext>(i);
		}
		public Exp_fatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exp_fat; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterExp_fat(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitExp_fat(this);
		}
	}

	[RuleVersion(0)]
	public Exp_fatContext exp_fat() {
		Exp_fatContext _localctx = new Exp_fatContext(Context, State);
		EnterRule(_localctx, 10, RULE_exp_fat);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68; Match(NUM);
			State = 73;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==OPER_FAT) {
				{
				{
				State = 69; Match(OPER_FAT);
				State = 70; termo();
				}
				}
				State = 75;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Exp_relacionalContext : ParserRuleContext {
		public ITerminalNode OPE_RELAC() { return GetToken(IsicompParser.OPE_RELAC, 0); }
		public ITerminalNode[] ID() { return GetTokens(IsicompParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(IsicompParser.ID, i);
		}
		public ITerminalNode[] NUM() { return GetTokens(IsicompParser.NUM); }
		public ITerminalNode NUM(int i) {
			return GetToken(IsicompParser.NUM, i);
		}
		public Exp_relacionalContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exp_relacional; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterExp_relacional(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitExp_relacional(this);
		}
	}

	[RuleVersion(0)]
	public Exp_relacionalContext exp_relacional() {
		Exp_relacionalContext _localctx = new Exp_relacionalContext(Context, State);
		EnterRule(_localctx, 12, RULE_exp_relacional);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			_la = TokenStream.LA(1);
			if ( !(_la==ID || _la==NUM) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 77; Match(OPE_RELAC);
			State = 78;
			_la = TokenStream.LA(1);
			if ( !(_la==ID || _la==NUM) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TermoContext : ParserRuleContext {
		public ITerminalNode NUM() { return GetToken(IsicompParser.NUM, 0); }
		public ITerminalNode ID() { return GetToken(IsicompParser.ID, 0); }
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public Exp_terContext exp_ter() {
			return GetRuleContext<Exp_terContext>(0);
		}
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public TermoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_termo; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterTermo(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitTermo(this);
		}
	}

	[RuleVersion(0)]
	public TermoContext termo() {
		TermoContext _localctx = new TermoContext(Context, State);
		EnterRule(_localctx, 14, RULE_termo);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NUM:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80; Match(NUM);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 81; Match(ID);
				}
				break;
			case T_APARENT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 82; Match(T_APARENT);
				State = 83; exp_ter();
				State = 84; Match(T_FPARENT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SeContext : ParserRuleContext {
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public Exp_relacionalContext exp_relacional() {
			return GetRuleContext<Exp_relacionalContext>(0);
		}
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public BlococomandoContext[] blococomando() {
			return GetRuleContexts<BlococomandoContext>();
		}
		public BlococomandoContext blococomando(int i) {
			return GetRuleContext<BlococomandoContext>(i);
		}
		public SeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_se; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterSe(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitSe(this);
		}
	}

	[RuleVersion(0)]
	public SeContext se() {
		SeContext _localctx = new SeContext(Context, State);
		EnterRule(_localctx, 16, RULE_se);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88; Match(T__3);
			State = 89; Match(T_APARENT);
			State = 90; exp_relacional();
			State = 91; Match(T_FPARENT);
			State = 92; Match(T__4);
			State = 93; blococomando();
			State = 97;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				{
				State = 94; Match(T__5);
				State = 95; Match(T__4);
				State = 96; blococomando();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtribuaContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(IsicompParser.ID, 0); }
		public ITerminalNode T_IGUAL() { return GetToken(IsicompParser.T_IGUAL, 0); }
		public Exp_terContext exp_ter() {
			return GetRuleContext<Exp_terContext>(0);
		}
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public AtribuaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atribua; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterAtribua(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitAtribua(this);
		}
	}

	[RuleVersion(0)]
	public AtribuaContext atribua() {
		AtribuaContext _localctx = new AtribuaContext(Context, State);
		EnterRule(_localctx, 18, RULE_atribua);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; Match(ID);
			State = 100; Match(T_IGUAL);
			State = 101; exp_ter();
			State = 102; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EscrevaContext : ParserRuleContext {
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public ITerminalNode ID() { return GetToken(IsicompParser.ID, 0); }
		public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public EscrevaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_escreva; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterEscreva(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitEscreva(this);
		}
	}

	[RuleVersion(0)]
	public EscrevaContext escreva() {
		EscrevaContext _localctx = new EscrevaContext(Context, State);
		EnterRule(_localctx, 20, RULE_escreva);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104; Match(T__6);
			State = 105; Match(T_APARENT);
			State = 108;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
				{
				State = 106; Match(ID);
				}
				break;
			case T_ASPAS:
				{
				State = 107; @string();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 110; Match(T_FPARENT);
			State = 111; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LeiaContext : ParserRuleContext {
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public ITerminalNode ID() { return GetToken(IsicompParser.ID, 0); }
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public LeiaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_leia; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterLeia(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitLeia(this);
		}
	}

	[RuleVersion(0)]
	public LeiaContext leia() {
		LeiaContext _localctx = new LeiaContext(Context, State);
		EnterRule(_localctx, 22, RULE_leia);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113; Match(T__7);
			State = 114; Match(T_APARENT);
			State = 115; Match(ID);
			State = 116; Match(T_FPARENT);
			State = 117; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnquantoContext : ParserRuleContext {
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public Exp_relacionalContext exp_relacional() {
			return GetRuleContext<Exp_relacionalContext>(0);
		}
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public ITerminalNode T_ACHAVE() { return GetToken(IsicompParser.T_ACHAVE, 0); }
		public BlococomandoContext blococomando() {
			return GetRuleContext<BlococomandoContext>(0);
		}
		public ITerminalNode T_FCHAVE() { return GetToken(IsicompParser.T_FCHAVE, 0); }
		public EnquantoContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enquanto; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterEnquanto(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitEnquanto(this);
		}
	}

	[RuleVersion(0)]
	public EnquantoContext enquanto() {
		EnquantoContext _localctx = new EnquantoContext(Context, State);
		EnterRule(_localctx, 24, RULE_enquanto);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119; Match(T__8);
			State = 120; Match(T_APARENT);
			State = 121; exp_relacional();
			State = 122; Match(T_FPARENT);
			State = 123; Match(T_ACHAVE);
			State = 124; blococomando();
			State = 125; Match(T_FCHAVE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FacaContext : ParserRuleContext {
		public ITerminalNode T_ACHAVE() { return GetToken(IsicompParser.T_ACHAVE, 0); }
		public BlococomandoContext blococomando() {
			return GetRuleContext<BlococomandoContext>(0);
		}
		public ITerminalNode T_FCHAVE() { return GetToken(IsicompParser.T_FCHAVE, 0); }
		public ITerminalNode T_APARENT() { return GetToken(IsicompParser.T_APARENT, 0); }
		public Exp_relacionalContext exp_relacional() {
			return GetRuleContext<Exp_relacionalContext>(0);
		}
		public ITerminalNode T_FPARENT() { return GetToken(IsicompParser.T_FPARENT, 0); }
		public ITerminalNode T_DOT() { return GetToken(IsicompParser.T_DOT, 0); }
		public FacaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_faca; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterFaca(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitFaca(this);
		}
	}

	[RuleVersion(0)]
	public FacaContext faca() {
		FacaContext _localctx = new FacaContext(Context, State);
		EnterRule(_localctx, 26, RULE_faca);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 127; Match(T__9);
			State = 128; Match(T_ACHAVE);
			State = 129; blococomando();
			State = 130; Match(T_FCHAVE);
			State = 131; Match(T__8);
			State = 132; Match(T_APARENT);
			State = 133; exp_relacional();
			State = 134; Match(T_FPARENT);
			State = 135; Match(T_DOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		public ITerminalNode[] T_ASPAS() { return GetTokens(IsicompParser.T_ASPAS); }
		public ITerminalNode T_ASPAS(int i) {
			return GetToken(IsicompParser.T_ASPAS, i);
		}
		public ITerminalNode[] LETTER() { return GetTokens(IsicompParser.LETTER); }
		public ITerminalNode LETTER(int i) {
			return GetToken(IsicompParser.LETTER, i);
		}
		public ITerminalNode[] NUM() { return GetTokens(IsicompParser.NUM); }
		public ITerminalNode NUM(int i) {
			return GetToken(IsicompParser.NUM, i);
		}
		public ITerminalNode[] WS() { return GetTokens(IsicompParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(IsicompParser.WS, i);
		}
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		public override void EnterRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.EnterString(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IIsicompListener typedListener = listener as IIsicompListener;
			if (typedListener != null) typedListener.ExitString(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 28, RULE_string);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137; Match(T_ASPAS);
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 138;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NUM) | (1L << LETTER) | (1L << WS))) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 141;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NUM) | (1L << LETTER) | (1L << WS))) != 0) );
			State = 143; Match(T_ASPAS);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x30', '\x94', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		'+', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '.', '\v', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x6', '\x4', '\x33', '\n', '\x4', 
		'\r', '\x4', '\xE', '\x4', '\x34', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', '=', '\n', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '\x42', 
		'\n', '\x6', '\f', '\x6', '\xE', '\x6', '\x45', '\v', '\x6', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\a', '\a', 'J', '\n', '\a', '\f', '\a', '\xE', 
		'\a', 'M', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x5', '\t', 'Y', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x5', '\n', '\x64', '\n', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x5', '\f', 'o', '\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', 
		'\x10', '\x6', '\x10', '\x8E', '\n', '\x10', '\r', '\x10', '\xE', '\x10', 
		'\x8F', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x2', '\x2', '\x11', 
		'\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', 
		'\x16', '\x18', '\x1A', '\x1C', '\x1E', '\x2', '\x4', '\x4', '\x2', '\xE', 
		'\xE', '\x12', '\x12', '\x5', '\x2', '\x12', '\x12', '\x15', '\x15', '\x30', 
		'\x30', '\x2', '\x92', '\x2', ' ', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'&', '\x3', '\x2', '\x2', '\x2', '\x6', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\b', '<', '\x3', '\x2', '\x2', '\x2', '\n', '>', '\x3', '\x2', '\x2', 
		'\x2', '\f', '\x46', '\x3', '\x2', '\x2', '\x2', '\xE', 'N', '\x3', '\x2', 
		'\x2', '\x2', '\x10', 'X', '\x3', '\x2', '\x2', '\x2', '\x12', 'Z', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x65', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'j', '\x3', '\x2', '\x2', '\x2', '\x18', 's', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', 'y', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\x8B', '\x3', '\x2', '\x2', '\x2', ' ', '!', '\a', 
		'\x3', '\x2', '\x2', '!', '\"', '\x5', '\x4', '\x3', '\x2', '\"', '#', 
		'\x5', '\x6', '\x4', '\x2', '#', '$', '\a', '\x4', '\x2', '\x2', '$', 
		'%', '\a', '(', '\x2', '\x2', '%', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'&', '\'', '\a', '\x5', '\x2', '\x2', '\'', ',', '\a', '\xE', '\x2', '\x2', 
		'(', ')', '\a', '$', '\x2', '\x2', ')', '+', '\a', '\xE', '\x2', '\x2', 
		'*', '(', '\x3', '\x2', '\x2', '\x2', '+', '.', '\x3', '\x2', '\x2', '\x2', 
		',', '*', '\x3', '\x2', '\x2', '\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', 
		'-', '/', '\x3', '\x2', '\x2', '\x2', '.', ',', '\x3', '\x2', '\x2', '\x2', 
		'/', '\x30', '\a', '(', '\x2', '\x2', '\x30', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\x33', '\x5', '\b', '\x5', '\x2', '\x32', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\a', '\x3', '\x2', '\x2', '\x2', '\x36', '=', '\x5', '\x18', 
		'\r', '\x2', '\x37', '=', '\x5', '\x16', '\f', '\x2', '\x38', '=', '\x5', 
		'\x14', '\v', '\x2', '\x39', '=', '\x5', '\x12', '\n', '\x2', ':', '=', 
		'\x5', '\x1A', '\xE', '\x2', ';', '=', '\x5', '\x1C', '\xF', '\x2', '<', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '<', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '<', '\x38', '\x3', '\x2', '\x2', '\x2', '<', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '<', ';', '\x3', '\x2', 
		'\x2', '\x2', '=', '\t', '\x3', '\x2', '\x2', '\x2', '>', '\x43', '\x5', 
		'\f', '\a', '\x2', '?', '@', '\a', '\xF', '\x2', '\x2', '@', '\x42', '\x5', 
		'\f', '\a', '\x2', '\x41', '?', '\x3', '\x2', '\x2', '\x2', '\x42', '\x45', 
		'\x3', '\x2', '\x2', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x45', '\x43', '\x3', '\x2', '\x2', '\x2', '\x46', 'K', 
		'\a', '\x12', '\x2', '\x2', 'G', 'H', '\a', '\x10', '\x2', '\x2', 'H', 
		'J', '\x5', '\x10', '\t', '\x2', 'I', 'G', '\x3', '\x2', '\x2', '\x2', 
		'J', 'M', '\x3', '\x2', '\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\x3', '\x2', '\x2', '\x2', 'L', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'K', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\t', '\x2', '\x2', 
		'\x2', 'O', 'P', '\a', '\x13', '\x2', '\x2', 'P', 'Q', '\t', '\x2', '\x2', 
		'\x2', 'Q', '\xF', '\x3', '\x2', '\x2', '\x2', 'R', 'Y', '\a', '\x12', 
		'\x2', '\x2', 'S', 'Y', '\a', '\xE', '\x2', '\x2', 'T', 'U', '\a', '%', 
		'\x2', '\x2', 'U', 'V', '\x5', '\n', '\x6', '\x2', 'V', 'W', '\a', '&', 
		'\x2', '\x2', 'W', 'Y', '\x3', '\x2', '\x2', '\x2', 'X', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'S', '\x3', '\x2', '\x2', '\x2', 'X', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'Y', '\x11', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', 
		'\x6', '\x2', '\x2', '[', '\\', '\a', '%', '\x2', '\x2', '\\', ']', '\x5', 
		'\xE', '\b', '\x2', ']', '^', '\a', '&', '\x2', '\x2', '^', '_', '\a', 
		'\a', '\x2', '\x2', '_', '\x63', '\x5', '\x6', '\x4', '\x2', '`', '\x61', 
		'\a', '\b', '\x2', '\x2', '\x61', '\x62', '\a', '\a', '\x2', '\x2', '\x62', 
		'\x64', '\x5', '\x6', '\x4', '\x2', '\x63', '`', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x65', '\x66', '\a', '\xE', '\x2', '\x2', '\x66', 
		'g', '\a', '#', '\x2', '\x2', 'g', 'h', '\x5', '\n', '\x6', '\x2', 'h', 
		'i', '\a', '(', '\x2', '\x2', 'i', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'j', 'k', '\a', '\t', '\x2', '\x2', 'k', 'n', '\a', '%', '\x2', '\x2', 
		'l', 'o', '\a', '\xE', '\x2', '\x2', 'm', 'o', '\x5', '\x1E', '\x10', 
		'\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', '&', '\x2', 
		'\x2', 'q', 'r', '\a', '(', '\x2', '\x2', 'r', '\x17', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '\n', '\x2', '\x2', 't', 'u', '\a', '%', '\x2', 
		'\x2', 'u', 'v', '\a', '\xE', '\x2', '\x2', 'v', 'w', '\a', '&', '\x2', 
		'\x2', 'w', 'x', '\a', '(', '\x2', '\x2', 'x', '\x19', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\a', '\v', '\x2', '\x2', 'z', '{', '\a', '%', '\x2', 
		'\x2', '{', '|', '\x5', '\xE', '\b', '\x2', '|', '}', '\a', '&', '\x2', 
		'\x2', '}', '~', '\a', '*', '\x2', '\x2', '~', '\x7F', '\x5', '\x6', '\x4', 
		'\x2', '\x7F', '\x80', '\a', '+', '\x2', '\x2', '\x80', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\a', '\f', '\x2', '\x2', '\x82', 
		'\x83', '\a', '*', '\x2', '\x2', '\x83', '\x84', '\x5', '\x6', '\x4', 
		'\x2', '\x84', '\x85', '\a', '+', '\x2', '\x2', '\x85', '\x86', '\a', 
		'\v', '\x2', '\x2', '\x86', '\x87', '\a', '%', '\x2', '\x2', '\x87', '\x88', 
		'\x5', '\xE', '\b', '\x2', '\x88', '\x89', '\a', '&', '\x2', '\x2', '\x89', 
		'\x8A', '\a', '(', '\x2', '\x2', '\x8A', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8D', '\a', '\'', '\x2', '\x2', '\x8C', '\x8E', '\t', 
		'\x3', '\x2', '\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x92', '\a', '\'', '\x2', '\x2', '\x92', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\v', ',', '\x34', '<', '\x43', 'K', 
		'X', '\x63', 'n', '\x8F',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
