//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Isicomp.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IsicompParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IIsicompListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrograma([NotNull] IsicompParser.ProgramaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrograma([NotNull] IsicompParser.ProgramaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] IsicompParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] IsicompParser.DeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.blococomando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlococomando([NotNull] IsicompParser.BlococomandoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.blococomando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlococomando([NotNull] IsicompParser.BlococomandoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComando([NotNull] IsicompParser.ComandoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComando([NotNull] IsicompParser.ComandoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.exp_ter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_ter([NotNull] IsicompParser.Exp_terContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.exp_ter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_ter([NotNull] IsicompParser.Exp_terContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.exp_fat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_fat([NotNull] IsicompParser.Exp_fatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.exp_fat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_fat([NotNull] IsicompParser.Exp_fatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.exp_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_relacional([NotNull] IsicompParser.Exp_relacionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.exp_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_relacional([NotNull] IsicompParser.Exp_relacionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermo([NotNull] IsicompParser.TermoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermo([NotNull] IsicompParser.TermoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.se"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSe([NotNull] IsicompParser.SeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.se"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSe([NotNull] IsicompParser.SeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.atribua"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtribua([NotNull] IsicompParser.AtribuaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.atribua"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtribua([NotNull] IsicompParser.AtribuaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.escreva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEscreva([NotNull] IsicompParser.EscrevaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.escreva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEscreva([NotNull] IsicompParser.EscrevaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.leia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeia([NotNull] IsicompParser.LeiaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.leia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeia([NotNull] IsicompParser.LeiaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnquanto([NotNull] IsicompParser.EnquantoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnquanto([NotNull] IsicompParser.EnquantoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.faca"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFaca([NotNull] IsicompParser.FacaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.faca"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFaca([NotNull] IsicompParser.FacaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsicompParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] IsicompParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsicompParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] IsicompParser.StringContext context);
}
