//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Isicomp.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="IsicompParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IIsicompVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.programa"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrograma([NotNull] IsicompParser.ProgramaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.declare"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare([NotNull] IsicompParser.DeclareContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.blococomando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlococomando([NotNull] IsicompParser.BlococomandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.comando"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] IsicompParser.ComandoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.exp_ter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_ter([NotNull] IsicompParser.Exp_terContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.exp_fat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_fat([NotNull] IsicompParser.Exp_fatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.exp_relacional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_relacional([NotNull] IsicompParser.Exp_relacionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.termo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTermo([NotNull] IsicompParser.TermoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.se"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSe([NotNull] IsicompParser.SeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.atribua"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtribua([NotNull] IsicompParser.AtribuaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.escreva"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEscreva([NotNull] IsicompParser.EscrevaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.leia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeia([NotNull] IsicompParser.LeiaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.enquanto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnquanto([NotNull] IsicompParser.EnquantoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.faca"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFaca([NotNull] IsicompParser.FacaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsicompParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] IsicompParser.StringContext context);
}
